-- MySQL Script generated by MySQL Workbench
-- Tue May  7 18:20:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kyky
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kyky
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kyky` DEFAULT CHARACTER SET utf8 ;
USE `kyky` ;

-- -----------------------------------------------------
-- Table `kyky`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyky`.`USER` (
  `USER_ID` INT NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kyky`.`PHOTO_POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kyky`.`PHOTO_POST` (
  `POST_ID` INT NOT NULL,
  `DECSRIPTION` VARCHAR(45) NOT NULL,
  `CREATE_DATE` DATETIME NOT NULL,
  `PHOTO_LINK` VARCHAR(45) NOT NULL,
  `USER_ID` INT NOT NULL,
  PRIMARY KEY (`POST_ID`),
  UNIQUE INDEX `POST_ID_UNIQUE` (`POST_ID` ASC) VISIBLE,
  INDEX `fk_PHOTO_POST_USER_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PHOTO_POST_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `kyky`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `kyky`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `kyky`;
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (123, 'jann_9991');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (124, 'kiakh');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (125, 'sasha');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (126, 'krokodil');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (127, 'gena');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (128, 'chebyrashka');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (129, 'hodko');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (130, 'glebek2h');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (131, 'pavel_belpohod');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (132, 'slasti_by');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (133, 'woman.dress');
INSERT INTO `kyky`.`USER` (`USER_ID`, `NAME`) VALUES (134, 'hi');

COMMIT;


-- -----------------------------------------------------
-- Data for table `kyky`.`PHOTO_POST`
-- -----------------------------------------------------
START TRANSACTION;
USE `kyky`;
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (1, '1 post', '12.11.2013', '1.jpg', 123);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (2, '2 post', '12.11.2011', '2.jpg', 124);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (3, '3 post', '12.11.2001', '3.jpg', 125);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (4, '4 post', '12.11.2010', '4.jpg', 126);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (5, '5 post', '12.11.2003', '5.jpg', 127);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (6, '6 post', '12.11.2011', '6.jpg', 128);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (7, '7 post', '12.11.2019', '7.jpg', 129);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (8, '8 post', '12.11.2017', '8.jpg', 130);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (9, '9 post', '12.11.2018', '9.jpg', 131);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (10, '10  post', '12.11.2016', '10.jpg', 132);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (11, '11 post', '12.11.2015', '11.jpg', 133);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (12, '12 post', '12.11.2013', '12.jpg', 134);
INSERT INTO `kyky`.`PHOTO_POST` (`POST_ID`, `DECSRIPTION`, `CREATE_DATE`, `PHOTO_LINK`, `USER_ID`) VALUES (DEFAULT, DEFAULT, '', DEFAULT, DEFAULT);

COMMIT;

